### ISSUE TITLE
Valida isEmail fails for most new domains

### ISSUE THREAD

**Issue by leeprobert** [highercomve/react-valida-hook#1]
Not sure if this is something you can fix in your code to make the email validation more robust, but currently it doesn't recognise modern domain names like .co, .tv, .ai etc as valid. Any idea how to reduce the validation rules so it accepts anything with an @ and a dot? Or even just the @? Validation is way too tricky for emails nowadays.

**Comment by highercomve** [comment]
Hi @leeprobert we could change the email received pattern in other to look for 2 digits or more after the dot.

That will work no?

**Comment by leeprobert** [comment]
Yes. Does it currently expect three? Classic .com etc? Does it also handle .co.uk? I noticed that Valida does also have a specific regex option, but I'm not sure how to implement it.

**Comment by highercomve** [comment]
Hello @leeprobert 

I changed how the emails are validated inside on valida-js dependency maybe you will need to update this package. In order to update the dependency

**Comment by keyranova** [comment]
@highercomve just updated to 0.0.5 and tried the examples @leeprobert put above. I'm not seeing a difference.

**Comment by highercomve** [comment]
Totally true @kurtnovack 

My mistake, I published the new version without update the valida-js version dependency.

I Just publish the 0.0.6 now corrected

Here an example

https://frontarm.com/demoboard/?id=b7b836cc-327f-4061-9aeb-621458064c97

**Comment by keyranova** [comment]
Thanks! @highercomve.

And just a thought: there are some similar packages that make use of https://github.com/jquense/yup for validation, any consideration on supporting it? It's extremely feature rich and you can just focus on the hooks side of this. (Unless you find it fun doing both, which I completely can relate to 😁)

**Comment by highercomve** [comment]
This closes https://github.com/highercomve/react-valida-hook/commit/bb005baa8dde0dc507c7a1e7ddea5c26457d7b3d #34

**Comment by highercomve** [comment]
> Thanks! @highercomve.
> 
> And just a thought: there are some similar packages that make use of https://github.com/jquense/yup for validation, any consideration on supporting it? It's extremely feature rich and you can just focus on the hooks side of this. (Unless you find it fun doing both, which I completely can relate to 😁)

Yeah, I'm having fun doing both. But maybe we could create another hook base on yup
