### ISSUE TITLE
TS7016 Could not find a declaration file for module 'react-valida-hook'

### ISSUE THREAD

**Issue by victorcarvalhosp** [highercomve/react-valida-hook#8]
Hi,

When using this library in a typescript project I got this error message: 
TS7016 Could not find a declaration file for module 'react-valida-hook'

The @types/react-valida-hook is not available too.

Yours,
Victor

**Comment by highercomve** [comment]
Hello victor, that is normal, because of the library doesn't have a typescript types definition. Is pure Javascript, I guess I should create those  typescript definitions.

I will try to do it this week
